websites:
  - name: "Target"
    product_url: "https://www.target.com/p/pok--233-mon-trading-card-game--scarlet---38--violet--8212-prismatic-evolutions-surprise-box--no-aasa/-/A-94336414"
    login_url: "https://www.target.com/account/sign-in"
    checkout_url: "https://www.target.com/co-review"
    max_price: 23
    quantity: 1
    selectors:
      login:
        email: "input#username"
        password: "input#password"
        login_button: "button[data-test='login-button']"
      price: "span[data-test='product-price']"
      add_to_cart: "button[id^='addToCartButtonOrTextIdFor'], button[data-test='shippingButton'], button[data-test='orderPickupButton']"
      view_cart: "div.styles_contentWrapper__p20AZ a"
      checkout: "button[data-test='checkoutButton']"
      checkout_password: "input[data-test='login-password']"
      checkout_sign_in_button: "button#login"
      captcha: "iframe[src*='captcha']"
      payment:
        card_number: "input[name='cardNumber']"
        expiry: "input[name='expiry']"
        cvv: "input[name='cvv']"
        submit_button: "button[data-test='placeOrderButton']"

  - name: "Target"
    product_url: "https://www.target.com/p/pok--233-mon-trading-card-game--scarlet---38--violet--8212-prismatic-evolutions-elite-trainer-box--no-aasa/-/A-93954435"
    login_url: "https://www.target.com/account/sign-in"
    checkout_url: "https://www.target.com/co-review"
    max_price: 55
    quantity: 1
    selectors:
      login:
        email: "input#username"
        password: "input#password"
        login_button: "button[data-test='login-button']"
      price: "span[data-test='product-price']"
      add_to_cart: "button[id^='addToCartButtonOrTextIdFor'], button[data-test='shippingButton'], button[data-test='orderPickupButton']"
      view_cart: "div.styles_contentWrapper__p20AZ a"
      checkout: "button[data-test='checkoutButton']"
      checkout_password: "input[data-test='login-password']"
      checkout_sign_in_button: "button#login"
      captcha: "iframe[src*='captcha']"
      payment:
        card_number: "input[name='cardNumber']"
        expiry: "input[name='expiry']"
        cvv: "input[name='cvv']"
        submit_button: "button[data-test='placeOrderButton']"

  - name: "Target"
    product_url: "https://www.target.com/p/pokemon-scarlet-violet-s3-5-booster-bundle-box--no-aasa/-/A-88897904"
    login_url: "https://www.target.com/account/sign-in"
    checkout_url: "https://www.target.com/co-review"
    max_price: 28
    quantity: 1
    selectors:
      login:
        email: "input#username"
        password: "input#password"
        login_button: "button[data-test='login-button']"
      price: "span[data-test='product-price']"
      add_to_cart: "button[id^='addToCartButtonOrTextIdFor'], button[data-test='shippingButton'], button[data-test='orderPickupButton']"
      view_cart: "div.styles_contentWrapper__p20AZ a"
      checkout: "button[data-test='checkoutButton']"
      checkout_password: "input[data-test='login-password']"
      checkout_sign_in_button: "button#login"
      captcha: "iframe[src*='captcha']"
      payment:
        card_number: "input[name='cardNumber']"
        expiry: "input[name='expiry']"
        cvv: "input[name='cvv']"
        submit_button: "button[data-test='placeOrderButton']"
        
