websites:
  - name: "Target - Prismatic Evolutions Elite Trainer Box"
    product_url: "https://www.target.com/p/pokemon-trading-card-game-scarlet-violet-elite-trainer-box/-/A-93954435"
    login_url: "https://www.target.com/account/sign-in"
    checkout_url: "https://www.target.com/co-review"
    max_price: 55
    quantity: 1
    selectors:
      login:
        email: "input#username"
        password: "input#password"
        login_button: "button[data-test='login-button']"
      stock: "div.h-margin-t-default span span"
      price: "span[data-test='product-price']"
      add_to_cart: "#addToCartButtonOrTextIdFor93954435"
      view_cart: "a[href='/cart']"
      checkout: "button[data-test='checkoutButton']"
      checkout_password: "input[data-test='login-password']"
      checkout_sign_in_button: "button#login"
      captcha: "iframe[src*='captcha']"
      payment:
        card_number: "input[name='cardNumber']"
        expiry: "input[name='expiry']"
        cvv: "input[name='cvv']"
        submit_button: "button[data-test='placeOrderButton']"
